update script to work with new qobuz player
tiliado/nuvola-app-qobuz pull request #7
Opened 2020-09-28 12:20 UTC by Romunix

Hello,

I fixed the qobuz integration on my PC and as there is no more maintainer, i create an account and i send you the patch.
The patch fix MPRIS2 integration and Multimedia keys.

Issue: tiliado/nuvolaruntime#619
Issue: tiliado/nuvolaruntime#634

2020-09-28 20:00 UTC, fenryxo requested changes
Thanks for your PR. Could you run `standard --fix` from ]Nuvola ADK](https://github.com/tiliado/nuvolaruntime/wiki/Nuvola-App-Developer-Kit) to fix the coding style? Thanks.

2020-10-02 06:53 UTC, Romunix commented
I have installed  Nuvola ADK and i have launched the command. Now i'm ready for maintenance.

2020-10-02 14:05 UTC, fenryxo requested changes
Code looks good :-)

* Could you add yourself (`Copyright 2020 Name <email>`) to the list of copyright holders in `README.md` and at the top of `integrate.js`?
* Could you update `CHANGELOG.md`?

2020-10-05 07:06 UTC, Romunix commented
Files updated ;-)

2020-10-05 14:29 UTC, fenryxo approved these changes

2020-10-05 14:30 UTC, merged

2020-10-05 15:13 UTC, fenryxo commented on CHANGELOG.md
> +------------------------
We write the release number and date when a release is made. I've changed it to `unreleased`.

2020-10-05 15:14 UTC, fenryxo commented
Merged and fresh flatpak packages published.